# Site settings
title: DRAIN.tips
email: bottom@drain.tips
description: Theory of Inventive Problem Solving for Deep Recursive AI Neural Networks ... and the law of unintended consequences from any brilliant solution.
twitter_username: DRAIN_tips
github_username:  DRAINtips

# Build settings
markdown: kramdown
