# Site settings
title: DRAIN.tips
email: bottom@drain.tips
description: Theory of Inventive Problem Solving for Deep Recursive AI Neural Nets and the Law of Unintended Consequences from any brilliant solution.
twitter_username: DRAIN_tips
github_username:  DRAINtips

# Build settings
markdown: kramdown
